### ISSUE TITLE
Mapping Between MIDI Channels And Stepper Motors

### ISSUE THREAD

**Issue by swiz23** [barlowtj48/MIDI-Stepper-Motor-Music#12]
Hi,

Thanks for creating this repo! This isn't so much an issue than a question. Is there somewhere in the documentation that shows the mapping between MIDI channels and stepper motors? I think that could be helpful as a check to make sure my project is working out correctly.

Also, as a different question, is there a free MIDI editor that you'd recommend? I was playing around with MuseCore (which has a great UI) but it looks like it doesn't do a good job of separating out multiple channels when outputting to a single MIDI port (though maybe I missed something). Cakewalk does separate out multiple channels, but the UI is a little daunting.

Thanks

**Comment by barlowtj48** [comment]
As far as the channels go, it is mostly as it is defined at the top of [midi_interface.ino](https://github.com/barlowtj48/MIDI-Stepper-Motor-Music/blob/021ba0ee32a4f8101e92716dce6a4c5749eaf742/midi_interface/midi_interface_4_motors.ino#L24)
Channel 1: X axis
Channel 2: Z axis
Channel 3: Y axis
Channel 4: A Axis

I don't have a good free MIDI editor unfortunately. I personally use FL studio, but I would say if you've found something else that supports it then it might be worth just crushing some YouTube videos to see if you can get going with that.

**Comment by swiz23** [comment]
Thanks
