### ISSUE TITLE
Request for sample files

### ISSUE THREAD

**Issue by richardguerre** [barlowtj48/MIDI-Stepper-Motor-Music#2]
Hi @barlowtj48, really cool project! I'm on a Mac so I can't use LoopMidi, so I modified the python script to accept a MIDI file directly, but it's not that fast for experimenting. Do you have the MIDI file you used for the Son of Flynn cover you made on TikTok (so cool btw)?

**Comment by barlowtj48** [comment]
Yeah! I added the two Tron tracks that I made, and also the Mario Star Power one too
