### ISSUE TITLE
Missing license.

### ISSUE THREAD

**Issue by EJEmmett** [barlowtj48/MIDI-Stepper-Motor-Music#5]
Could you add a license to the project? 

On GitHub, without a defined license, the [default copyright laws apply](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license). Meaning no one can use or modify this code legally.

This [website](https://choosealicense.com/) could help you figure out how you want to license it if you do want to add one.

**Comment by barlowtj48** [comment]
Added MIT License 👍
